"""enrich order schema

Revision ID: 8da17bdab460
Revises: 539d935ea440
Create Date: 2025-10-05 04:37:04.327349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da17bdab460'
down_revision: Union[str, Sequence[str], None] = '539d935ea440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create
    op.add_column('customers', sa.Column('customer_type', sa.Enum('DEPARTMENT', 'CAMPUS', 'STUDENT', 'VENDOR', name='customer_types'), nullable=False))
    op.add_column('orders', sa.Column('priority', sa.Enum('STANDARD', 'URGENT', 'RUSH', name='order_priority'), nullable=False))
    op.add_column('orders', sa.Column('work_center_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'work_centers', ['work_center_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'work_center_id')
    op.drop_column('orders', 'priority')
    op.drop_column('customers', 'customer_type')
    op.drop_table('work_centers')
    # ### end Alembic commands ###
